#!/bin/bash

### pbp-pong ###

set -e
export SHELLOPTS

# set up env vars depending on whether this script was called from elsewhere or is the top level
if [ "$#" -eq 0 ]; then
    # no arguments - top level build
    # current working directory (of dtree)
    export PBP="${HOME}/projects/pbp-dev"
    export PBPWD="$(pwd)"
    export PBPCALLER=$PBPWD
    export PYTHONPATH="${PBP}/kernel:${PYTHONPATH}"
    ###
    dtree_tool=${HOME}/projects/dtree
    ${PBP}/resetlog
elif [ "$#" -eq 3 ]; then
    # exactly three arguments
    # $1 is callee's working dir (i.e. dtree)
    # $2 is name of decision tree .drawio file, 
    # $3 is caller's working dir
    # push a new value of PBPWD onto the stack, which will get unwound to its previous value when this script ends
    echo "Frishc is not callable (yet)"
    exit 1
else
    # error: usage
    echo "Usage: $0 [diagram callerWDIR]" >&2
    exit 1
fi

rm -f out.*
rm -f *.json

# create xinterpret.frish from xinterpret.drawio
${dtree_tool}/@make ${dtree_tool} "xinterpret" $PBPCALLER

# create forthish.frish by including the generated code from xinterpret.drawio
m4 forthish.frish.m4 | tr -d '\r' > forthish.frish

# convert the diagram frish.drawio to frish.drawio.json
${PBP}/das2json frish.drawio

# produce frishc.py by running the frish transmogrifier
python3 main.py 'forthish.frish' main frish.drawio.json | ${PBP}/splitoutputs
if [ -f out.✗ ]
then
    echo
    echo ">> ERROR <<"
    cat out.✗
else
    mv out.1.py frishc.py
fi
