#!/bin/bash

######### commands specific to this project #############
# env vars that may be used in this script:
#  $PATH
#  $TOOLWD ($(pwd))
#  $CALLERPATH
#  $TARGET
#  $PYTHONPATH

node ./pbp/das/das2json.mjs pong.drawio
python main.py '' main pong.drawio.json

############################



