#!/bin/bash
######### commands specific to this project #############

das2json pong.drawio
python main.py "pong.glsl" testkbd pong.drawio.json
rm -f ${SELF}*
stty sane
echo -n 'fini '


############################
