#!/bin/bash
######### commands specific to this project #############
# env vars that may be used in this script:
#  $PATH
#  $TOOLWD ($(pwd))
#  $CALLERPATH
#  $TARGET
#  $PYTHONPATH

cleanup() {
    stty sane
    local exit_code=$?
    echo "Exiting with code $exit_code"
    # Cleanup: rm -rf /tmp/mystuff
    exit $exit_code  # Preserve original status
}

trap cleanup ERR EXIT INT TERM

echo 'left paddle q a (up,down)'
echo 'right paddle p ; (up,down)'
echo 'ball h j k l (left down up right)'
echo

echo "making ballhit state machine"
@make "$(realpath ~/projects/sm-pbp)" "$(pwd)" ballhit
echo "DONE making ballhit state machine"

sourcecode=testgame

das2json pong.drawio
python main.py "pong.glsl" ${sourcecode} pong.drawio.json
stty sane
echo -n 'fini '


############################
