#!/bin/bash
# usage: ./run 'grammar' 'rewrite' 'support' 'src'
# (supply a library directory, a grammar file, a rewrite file, and a support (JS) file, inhale a source file (written in new nDSL syntax), exhale output of running the nanoDSL code
set -e
LIB=$1
GRAMMAR=$2
REWRITE=$3
SUPPORT=$4
SRC=$5
node ${LIB}/t2t.mjs ${REWRITE} >temp.REWRITE.mjs
cat \
    ${LIB}/front.part.js \
    ${GRAMMAR} \
    ${LIB}/middle.part.js \
    ${LIB}/args.part.js \
    ${SUPPORT} \
    temp.REWRITE.mjs \
    ${LIB}/tmxtail.part.js \
    >temp.TMX.mjs
# at this point temp.TMX.mjs is a .JS program that can be used to transpile ${SRC}
node temp.TMX.mjs ${SRC}
