#!/bin/bash

######### commands specific to this project #############
# env vars that may be used in this script:
#  $PATH
#  $TOOLWD ($(pwd))
#  $CALLERPATH
#  $1 (same as $TARGET)
#  $PYTHONPATH

output=/dev/stdout
./pbp/t2t $1 </dev/null >$output

############################



